### ISSUE TITLE
Can't Create Add New Addons If None Exist

### ISSUE THREAD

**Issue by rdegges** [heroku/heroku.py#16]
If you've got an application, and it currently has no addons, eg:

``` python
>>> app.addons
[]
```

You're unable to add any new addons until at least one exists:

``` python
>>> new_addon = app.addons.add('heroku-postgresql:dev')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rdegges/.virtualenvs/postgresly/local/lib/python2.7/site-packages/heroku/structures.py", line 50, in add
    return o.new(*args, **kwargs)
  File "/home/rdegges/.virtualenvs/postgresly/local/lib/python2.7/site-packages/heroku/models.py", line 126, in new
    resource=('apps', self.app.name, 'addons', name)
AttributeError: 'Addon' object has no attribute 'app'
```

So, the workaround (currently) is to add an addon manually using some other method (eg: the CLI tool), and then everything works as expected.

**Comment by edmorley** [comment]
This project has been deprecated for some time, and is now being sunset.

We recommend that you use the maintained https://github.com/martyzz1/heroku3.py instead.
